language: python

python:
    - 2.7
    -3.5
    -3.6

# install dependency
install: 
  -pip install -r requirements.txt
cache: pip

script: python -m pytest && coverage run -m pytest && coverage report
after_success: coveralls