language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirement.txt
  - pip install coveralls

script:
  - python3 -m pytest --cov=app tests/
  
after_success: 
  - coveralls
