language: python

python:
    -3.5

# install dependency
install: 
  -pip install -r requirements.txt
  -pip install coveralls
cache: pip

script:
  -python3 -m pytest --cov=app tests/
  
after_success: 
  -coveralls
