language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests -v --with-coverage --cover-package="app"
  
after_success: 
  - coveralls
