language: python

python:
    - "3.5"

# install dependency
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python3 -m pytest 
  - coverage run --source=app run.py test
  - coverage report
  
after_success: 
  - coveralls
