language: python

python:
    - "3.5"

# install dependency
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python3 -m pytest 
  - pytest --cov = app/
  
after_success: 
  - coveralls
