language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python3 -m pytest --cover-package=app tests/
  
after_success: 
  - coveralls
